### ISSUE TITLE
Uncaught Error: Assertion Failed: `modulePrefix` must be defined

### ISSUE THREAD

**Issue by bugduino** [dgeb/ember-engines-demo#2]
Hi,
I cloned the repo and did
`npm install && bower install`
`ember s`

but Visiting localhost:4200 causes the following error
`Uncaught Error: Assertion Failed:`modulePrefix`must be defined`

how can I fix this?

**Comment by PratheepV** [comment]
+1

**Comment by dgeb** [comment]
Thanks for reporting this. The reason for this failure, as well as some suggestions for better long term fixes, is explained in https://github.com/dgeb/ember-engines/issues/149
